In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
weather = pd.read_csv('weather_data.csv')
weather.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [4]:
# shape or data
weather.shape

(8784, 8)

In [5]:
# index 
weather.index

RangeIndex(start=0, stop=8784, step=1)

In [6]:
# columns names
weather.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [18]:
# know the datatypes of each columns
weather.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [21]:
print(weather.count)

<bound method DataFrame.count of              Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4
1        1/1/2012 1:00    -1.8              -3.7         87                4
2        1/1/2012 2:00    -1.8              -3.4         89                7
3        1/1/2012 3:00    -1.5              -3.2         88                6
4        1/1/2012 4:00    -1.5              -3.3         88                7
...                ...     ...               ...        ...              ...
8779  12/31/2012 19:00     0.1              -2.7         81               30
8780  12/31/2012 20:00     0.2              -2.4         83               24
8781  12/31/2012 21:00    -0.5              -1.5         93               28
8782  12/31/2012 22:00    -0.2              -1.8         89               28
8783  12/31/2012 23:00     0.0              -2.1         86               30

      Visibility_km  Press_kPa               Weather
0               8.0     101.24                   Fog
1               8.0     101.24                   Fog
2               4.0     101.26  Freezing Drizzle,Fog
3               4.0     101.27  Freezing Drizzle,Fog
4               4.8     101.23                   Fog
...             ...        ...                   ...
8779            9.7     100.13                  Snow
8780            9.7     100.03                  Snow
8781            4.8      99.95                  Snow
8782            9.7      99.91                  Snow
8783           11.3      99.89                  Snow

[8784 rows x 8 columns]>

In [22]:
weather.value_counts()

Date/Time        Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  Visibility_km  Press_kPa  Weather
1/1/2012 0:00    -1.8    -3.9              86         4                8.0            101.24     Fog             1
6/1/2012 12:00    19.3    3.3              35         20               48.3           101.32     Cloudy          1
5/9/2012 7:00     14.3    12.5             89         15               4.8            100.12     Fog             1
5/9/2012 8:00     14.3    12.3             88         17               6.4            100.12     Fog             1
5/9/2012 9:00     14.0    12.3             89         9                4.0            100.10     Drizzle,Fog     1
                                                                                                                ..
12/8/2012 3:00    2.1    -1.5              77         6                25.0           101.18     Cloudy          1
12/8/2012 2:00    2.0    -1.9              75         7                25.0           101.17     Cloudy          1
12/8/2012 23:00   1.3     0.6              95         17               8.0            100.96     Drizzle,Fog     1
12/8/2012 22:00   1.2     0.6              96         13               6.4            100.84     Fog             1
9/9/2012 9:00     14.8    8.8              67         17               48.3           100.65     Mainly Clear    1
Name: count, Length: 8784, dtype: int64

In [23]:
weather.info

<bound method DataFrame.info of              Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4
1        1/1/2012 1:00    -1.8              -3.7         87                4
2        1/1/2012 2:00    -1.8              -3.4         89                7
3        1/1/2012 3:00    -1.5              -3.2         88                6
4        1/1/2012 4:00    -1.5              -3.3         88                7
...                ...     ...               ...        ...              ...
8779  12/31/2012 19:00     0.1              -2.7         81               30
8780  12/31/2012 20:00     0.2              -2.4         83               24
8781  12/31/2012 21:00    -0.5              -1.5         93               28
8782  12/31/2012 22:00    -0.2              -1.8         89               28
8783  12/31/2012 23:00     0.0              -2.1         86               30

      Visibility_km  Press_kPa               Weather
0               8.0     101.24                   Fog
1               8.0     101.24                   Fog
2               4.0     101.26  Freezing Drizzle,Fog
3               4.0     101.27  Freezing Drizzle,Fog
4               4.8     101.23                   Fog
...             ...        ...                   ...
8779            9.7     100.13                  Snow
8780            9.7     100.03                  Snow
8781            4.8      99.95                  Snow
8782            9.7      99.91                  Snow
8783           11.3      99.89                  Snow

[8784 rows x 8 columns]>

In [28]:
weather.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [32]:
# find all unique wind speed values in the data
weather['Wind Speed_km/h'].unique().

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [30]:
weather['Wind Speed_km/h'].nunique()

34

In [33]:
# find the number of times when the weather is exactly clear
weather.sample(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
3049,5/7/2012 1:00,6.9,0.3,63,0,25.0,101.55,Clear
1072,2/14/2012 16:00,2.3,-4.9,59,7,24.1,100.97,Mostly Cloudy
5246,8/6/2012 14:00,22.5,13.0,55,13,48.3,101.15,Mostly Cloudy
7045,10/20/2012 13:00,17.6,10.6,64,11,48.3,99.75,Mainly Clear
1690,3/11/2012 10:00,3.8,-5.7,50,13,48.3,101.97,Clear

In [37]:
weather[weather['Weather'] == 'Clear' ]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [39]:
# find the number of times when the wind speed was exactly 4km/h
weather[weather['Wind Speed_km/h'] == 4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

In [40]:
# find out all the null values in data
weather.isnull()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False
8780,False,False,False,False,False,False,False,False
8781,False,False,False,False,False,False,False,False
8782,False,False,False,False,False,False,False,False
8783,False,False,False,False,False,False,False,False

In [41]:
#  Count null values in each column
weather.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [44]:
# rename the column name 'weather' to 'weather condition'
weather.rename(columns={'Weather': 'Weather Condition'}, inplace=True)
weather

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [45]:
# what is mean value of 'visibility'
weather['Visibility_km'].mean()

27.664446721311478

In [46]:
# standard derivation of pressure
weather['Press_kPa'].std()

0.8440047459486474

In [47]:
# variance of humnidity
weather['Rel Hum_%'].var()

286.2485501984998

In [49]:
# snow recorded and contains
weather[weather['Weather Condition'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [50]:
weather['Weather Condition'].contains('Snow')

AttributeError: 'Series' object has no attribute 'contains'

In [53]:
weather[weather['Weather Condition'].str.contains('Snow')].sample(50)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
8687,12/27/2012 23:00,-4.0,-5.6,89,24,9.7,100.70,Snow
8521,12/21/2012 1:00,1.1,-0.7,88,17,6.4,100.47,"Rain,Snow,Ice Pellets"
8458,12/18/2012 10:00,0.6,0.0,96,24,1.2,99.86,Snow
1314,2/24/2012 18:00,0.0,-1.4,90,24,1.0,99.07,Snow
177,1/8/2012 9:00,-6.4,-11.9,65,17,24.1,101.81,Snow
667,1/28/2012 19:00,2.2,-2.6,71,19,19.3,100.09,Snow
790,2/2/2012 22:00,-8.0,-11.5,76,7,25.0,102.29,Snow
7891,11/24/2012 19:00,-0.9,-5.0,74,22,19.3,99.90,Snow Showers
1322,2/25/2012 2:00,0.4,-0.9,91,11,6.4,98.06,Snow
8520,12/21/2012 0:00,1.9,-2.1,75,26,25.0,100.60,"Rain,Snow Grains"
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
8554,12/22/2012 10:00,-3.6,-5.0,90,37,1.6,98.70,Snow
8462,12/18/2012 14:00,1.0,0.2,94,24,4.0,99.53,Snow
8438,12/17/2012 14:00,0.8,0.1,95,19,4.0,100.65,"Snow,Fog"
8523,12/21/2012 3:00,0.9,0.0,94,28,4.8,100.12,"Rain,Snow,Ice Pellets"
1438,2/29/2012 22:00,-4.5,-12.3,54,30,25.0,101.14,Snow
8326,12/12/2012 22:00,-3.8,-5.6,87,4,11.3,102.40,Snow Showers
738,1/31/2012 18:00,-7.8,-11.2,77,20,1.6,101.18,Snow
986,2/11/2012 2:00,-8.6,-11.0,83,30,8.0,100.91,Snow
8155,12/5/2012 19:00,-1.0,-8.5,57,28,25.0,101.84,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
8478,12/19/2012 6:00,0.4,-0.1,96,9,2.4,100.05,"Drizzle,Snow,Fog"
8419,12/16/2012 19:00,-5.1,-6.6,89,22,16.1,101.20,Snow
276,1/12/2012 12:00,-5.8,-8.9,79,32,4.8,100.22,Snow
1332,2/25/2012 12:00,-2.5,-4.2,88,33,3.2,98.75,Snow
7400,11/4/2012 8:00,2.2,-1.2,78,17,24.1,101.11,"Rain Showers,Snow Showers"
389,1/17/2012 5:00,-8.3,-10.4,85,6,3.6,100.75,"Freezing Drizzle,Snow"
8428,12/17/2012 4:00,-3.0,-4.1,92,24,6.4,100.91,"Snow,Ice Pellets"
222,1/10/2012 6:00,0.7,-1.2,87,30,8.0,100.04,Snow
394,1/17/2012 10:00,-6.5,-9.0,82,15,1.2,100.60,Snow
8565,12/22/2012 21:00,-7.2,-11.6,71,28,16.1,99.96,Snow
8495,12/19/2012 23:00,0.6,-0.9,90,13,25.0,101.50,Snow
8413,12/16/2012 13:00,-8.0,-11.2,78,26,12.9,101.54,Snow
8547,12/22/2012 3:00,1.1,0.1,93,28,9.7,97.93,"Drizzle,Snow,Fog"
8777,12/31/2012 17:00,-1.1,-3.3,85,19,9.7,100.30,Snow
8530,12/21/2012 10:00,1.0,0.0,93,32,12.9,99.24,Snow
761,2/1/2012 17:00,-4.3,-7.1,81,0,6.4,100.61,"Snow,Haze"
8561,12/22/2012 17:00,-5.7,-8.5,81,32,6.4,99.50,Snow
8676,12/27/2012 12:00,-5.5,-6.6,92,39,0.6,100.50,"Moderate Snow,Blowing Snow"
1456,3/1/2012 16:00,-2.7,-5.7,80,19,2.4,100.74,Snow
8671,12/27/2012 7:00,-6.5,-7.6,92,44,1.2,100.73,Snow
1315,2/24/2012 19:00,0.0,-1.3,91,22,1.2,98.88,Snow
668,1/28/2012 20:00,1.7,-1.2,81,24,19.3,100.05,Snow
1771,3/14/2012 19:00,0.3,-0.2,96,15,8.0,102.07,"Snow,Fog"
8528,12/21/2012 8:00,0.8,-0.2,93,32,2.4,99.50,"Rain,Snow"
457,1/20/2012 1:00,-4.1,-8.3,73,20,25.0,100.54,Snow
983,2/10/2012 23:00,-0.9,-2.4,90,6,9.7,100.76,"Snow,Fog"
98,1/5/2012 2:00,-5.4,-8.3,80,9,8.0,100.28,Snow
1452,3/1/2012 12:00,-4.3,-6.8,83,30,1.2,100.66,Snow
723,1/31/2012 3:00,-6.8,-12.4,64,15,19.3,101.76,Snow

In [57]:
# wind is above 24 nd visibility is 25
weather[(weather['Wind Speed_km/h'] > 24) &  (weather['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [61]:
# mean value each columns
weather.groupby('Weather Condition').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [62]:
# min nd max each column against 'weather condition'

In [64]:
# weather contion in fog
weather[weather['Weather Condition'] == 'Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

In [68]:
# weather is clear or visibility above 40
weather[(weather['Weather Condition'] == 'Clear') & (weather['Visibility_km'] > 40)].sample(50)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
5142,8/2/2012 6:00,21.7,19.6,88,15,48.3,100.55,Clear
3977,6/14/2012 17:00,22.9,6.9,36,15,48.3,102.17,Clear
3016,5/5/2012 16:00,16.0,-2.4,28,17,48.3,101.51,Clear
4615,7/11/2012 7:00,18.2,9.6,57,4,48.3,101.73,Clear
352,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear
2219,4/2/2012 11:00,4.6,-7.8,40,24,48.3,100.72,Clear
2868,4/29/2012 12:00,7.4,-10.5,27,24,48.3,101.62,Clear
2317,4/6/2012 13:00,7.6,-7.7,33,15,48.3,101.18,Clear
3991,6/15/2012 7:00,16.8,8.8,59,19,48.3,102.38,Clear
440,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear
2312,4/6/2012 8:00,1.1,-8.8,48,19,48.3,101.34,Clear
4196,6/23/2012 20:00,23.5,5.4,31,6,48.3,100.88,Clear
5072,7/30/2012 8:00,22.4,16.7,70,7,48.3,101.31,Clear
5875,9/1/2012 19:00,20.9,8.3,44,6,48.3,101.45,Clear
1935,3/21/2012 15:00,25.4,12.0,43,17,48.3,101.72,Clear
2873,4/29/2012 17:00,9.0,-11.5,22,30,48.3,101.72,Clear
7646,11/14/2012 14:00,5.2,-6.2,44,6,48.3,103.15,Clear
2173,3/31/2012 13:00,6.5,-9.7,30,9,48.3,101.08,Clear
3974,6/14/2012 14:00,22.4,5.5,33,15,48.3,102.17,Clear
2478,4/13/2012 6:00,1.8,-3.4,68,6,48.3,101.67,Clear
5803,8/29/2012 19:00,21.7,6.7,38,15,48.3,100.89,Clear
6319,9/20/2012 7:00,9.6,6.9,83,9,48.3,101.95,Clear
3966,6/14/2012 6:00,14.7,6.3,57,9,48.3,102.20,Clear
3972,6/14/2012 12:00,21.3,4.7,34,24,48.3,102.26,Clear
6232,9/16/2012 16:00,16.6,3.0,40,15,48.3,101.20,Clear
4204,6/24/2012 4:00,14.4,9.0,70,11,48.3,101.04,Clear
1668,3/10/2012 12:00,-4.1,-12.1,54,7,48.3,102.99,Clear
6320,9/20/2012 8:00,11.7,7.6,76,7,48.3,101.94,Clear
4423,7/3/2012 7:00,20.3,10.3,53,6,48.3,100.97,Clear
951,2/9/2012 15:00,2.4,-6.2,53,24,48.3,101.03,Clear
2315,4/6/2012 11:00,5.7,-7.7,37,19,48.3,101.32,Clear
5237,8/6/2012 5:00,16.6,13.3,81,9,48.3,100.95,Clear
2871,4/29/2012 15:00,9.0,-12.0,21,32,48.3,101.63,Clear
1356,2/26/2012 12:00,-9.3,-18.6,47,28,48.3,102.42,Clear
5631,8/22/2012 15:00,25.7,10.9,39,20,48.3,101.33,Clear
924,2/8/2012 12:00,-4.6,-12.9,52,20,48.3,101.76,Clear
2599,4/18/2012 7:00,2.5,-6.2,53,13,48.3,102.44,Clear
4545,7/8/2012 9:00,20.6,8.5,46,20,48.3,100.81,Clear
2145,3/30/2012 9:00,-2.0,-10.1,54,13,48.3,101.63,Clear
4422,7/3/2012 6:00,18.5,11.1,62,9,48.3,100.98,Clear
3964,6/14/2012 4:00,12.4,4.9,60,15,48.3,102.04,Clear
3173,5/12/2012 5:00,7.3,-1.4,54,6,48.3,101.37,Clear
3054,5/7/2012 6:00,8.2,3.3,71,6,48.3,101.63,Clear
1567,3/6/2012 7:00,-14.8,-20.7,61,11,48.3,103.00,Clear
351,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear
3057,5/7/2012 9:00,16.0,-3.0,27,7,48.3,101.68,Clear
6318,9/20/2012 6:00,7.7,6.5,92,6,48.3,101.97,Clear
3058,5/7/2012 10:00,17.1,-5.9,20,13,48.3,101.67,Clear
6324,9/20/2012 12:00,17.6,7.3,51,15,48.3,101.56,Clear
3162,5/11/2012 18:00,16.8,-2.7,26,22,48.3,100.87,Clear

In [70]:
# weather is clean and humidity greather than 50, visibility is above 40
weather[(weather['Weather Condition'] == 'Clear') & ((weather['Rel Hum_%'] >= 50) & (weather['Visibility_km'] > 40))]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
351,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,1/18/2012 17:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,1/19/2012 9:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,12/15/2012 8:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,12/15/2012 9:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,12/15/2012 13:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,12/25/2012 15:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,12/25/2012 16:00,-7.5,-13.9,60,11,48.3,102.03,Clear